#!/bin/sh

DEVICE=$(cat /opt/inkbox_device)
if [ "${DEVICE}" != "n236" ] && [ "${DEVICE}" != "n437" ]; then
	BRIGHTNESS_SYSFS_FILE="/sys/class/backlight/mxc_msp430.0/brightness"
else
	if [ "${DEVICE}" == "n249" ]; then
		BRIGHTNESS_SYSFS_FILE="/sys/class/backlight/backlight_cold/brightness"
		WARM_BRIGHTNESS_SYSFS_FILE="/sys/class/backlight/backlight_warm/brightness"
	else
		BRIGHTNESS_SYSFS_FILE="/sys/class/backlight/mxc_msp430_fl.0/brightness"
	fi
fi
/opt/bin/wall "The system is going down for reboot NOW!"

if [ "${1}" != "no_splash" ]; then
	sleep 2
	/opt/bin/fbink/fbink -k -f -h -q -w
	/opt/bin/fbink/fbink -k -f -q -w
	/opt/bin/fbink/fbink -t regular=/etc/init.d/splash.d/fonts/resources/inter-b.ttf,size=20 "Rebooting" -m -M -q -w
	sleep 1
	if [ "${DEVICE}" == "n705" ] || [ "${DEVICE}" == "n905b" ] || [ "${DEVICE}" == "n905c" ] || [ "${DEVICE}" == "kt" ]; then
		:
	else
		/opt/bin/cinematic_brightness 0 0 -1 -1 3000 1
	fi
else
	if [ "${DEVICE}" == "n705" ] || [ "${DEVICE}" == "n905b" ] || [ "${DEVICE}" == "n905c" ] || [ "${DEVICE}" == "kt" ]; then
		:
	else
		if [ "${DEVICE}" == "n613" ]; then
			sleep 1
			/opt/bin/frontlight 0
		else
			echo 0 > "${BRIGHTNESS_SYSFS_FILE}"
			if [ "${DEVICE}" == "n249" ]; then
				echo 0 > "${WARM_BRIGHTNESS_SYSFS_FILE}"
			fi
		fi
	fi
fi

if [ "${2}" == "reset_kobox" ]; then
	/sbin/prepare_shutdown reboot reset_kobox
else
	/sbin/prepare_shutdown reboot
fi
