-- ./settings.reader.lua
return {
    ["plugins_disabled"] = {
        ["SSH"] = true,
        ["archiveviewer"] = true,
        ["autodim"] = true,
        ["autoturn"] = true,
        ["autowarmth"] = true,
        ["backgroundrunner"] = true,
        ["batterystat"] = true,
        ["bookshortcuts"] = true,
        ["calibre"] = true,
        ["coverbrowser"] = true,
        ["docsettingtweak"] = true,
        ["httpinspector"] = true,
        ["japanese"] = true,
        ["keepalive"] = true,
        ["kosync"] = true,
        ["movetoarchive"] = true,
        ["newsdownloader"] = true,
        ["opds"] = true,
        ["readtimer"] = true,
        ["statistics"] = true,
        ["systemstat"] = true,
        ["texteditor"] = true,
        ["vocabbuilder"] = true,
        ["wallabag"] = true,
    },
}
