-- ./settings.reader.lua
return {
    ["footer"] = {
        ["progress_style_thin"] = true,
        ["progress_style_thin_height"] = 4,
    },
    ["plugins_disabled"] = {
        ["SSH"] = true,
        ["archiveviewer"] = true,
        ["autodim"] = true,
        ["autoturn"] = true,
        ["autowarmth"] = true,
        ["backgroundrunner"] = true,
        ["batterystat"] = true,
        ["bookshortcuts"] = true,
        ["calibre"] = true,
        ["coverbrowser"] = true,
        ["docsettingtweak"] = true,
        ["httpinspector"] = true,
        ["japanese"] = true,
        ["keepalive"] = true,
        ["kosync"] = true,
        ["movetoarchive"] = true,
        ["newsdownloader"] = true,
        ["opds"] = true,
        ["readtimer"] = true,
        ["statistics"] = true,
        ["systemstat"] = true,
        ["texteditor"] = true,
        ["vocabbuilder"] = true,
        ["wallabag"] = true,
        ["calibrecompanion"] = true,
        ["evernote"] = true,
        ["exporter"] = true,
        ["goodreads"] = true,
        ["kobolight"] = true,
        ["send2ebook"] = true,
        ["storagestat"] = true,
        ["zsync"] = true,
    },
    ["kopt_page_scroll"] = 0,
    ["kopt_zoom_mode_type"] = 2,
}
